version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - laitingsheng
    assignees:
      - laitingsheng
    labels:
      - enhancement
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - laitingsheng
    assignees:
      - laitingsheng
    labels:
      - enhancement
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - laitingsheng
    assignees:
      - laitingsheng
    labels:
      - enhancement
