# -*- coding: utf-8 -*-
__all__ = ["LoggerIO"]

from io import TextIOBase


class LoggerIO(TextIOBase):
    def __init__(self, name: str, level: int) -> None: ...

    def isatty(self) -> bool: ...

    def readable(self) -> bool: ...

    def seekable(self) -> bool: ...

    def tell(self) -> int: ...

    def writable(self) -> bool: ...

    def write(self, s: str) -> int: ...
